// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-2',
  aws_cognito_identity_pool_id:
    'ap-northeast-2:8a333684-da29-4ec9-bd2d-77f38d44b5a2',
  aws_cognito_region: 'ap-northeast-2',
  aws_user_pools_id: 'ap-northeast-2_7gSBHlM5o',
  aws_user_pools_web_client_id: '3fvh6b2rec72k8cak4v16f3luc',
  aws_user_files_s3_bucket: 'wdd-client-file',
  aws_user_files_s3_bucket_region: 'ap-northeast-2',
};

export default awsmobile;
