// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'ap-northeast-2',
  aws_cognito_identity_pool_id:
    'ap-northeast-2:a9e659e3-e18c-4792-a33e-af30cab20726',
  aws_cognito_region: 'ap-northeast-2',
  aws_user_pools_id: 'ap-northeast-2_a501KRV0v',
  aws_user_pools_web_client_id: 'mlnba5u4eankf2nb6prq5h1hk',
  oauth: {},
  aws_user_files_s3_bucket: 'wdd-storage-root',
  aws_user_files_s3_bucket_region: 'ap-northeast-2',
};

export default awsmobile;
